- name: Basic System Setup
  hosts: web
  become: true
  vars:
    user_name: 'selma'
    package_state: 'latest'
    security_only: true
  tasks:
    - name: Update all security-related packages
      ansible.builtin.package:
        name: '*'
        state: "{{ package_state }}"
        security: "{{security_only}}"

    - name: Create a new user
      ansible.builtin.user:
        name: "{{ item }}"
        state: present
        create_home: true
      loop: 
        - alice
        - bob
        - carol

    - name: Install Apache on web server
      ansible.builtin.package:
        name: "{{package_name}}"
        state: present
      when: inventory_hostname in gorups['web']

    - name: Install firewalld
      ansible.builtin.package:
        name: firewalld
        state: present
      when: inventory_hostname in gorups['web']

    - name: Ensure firewalld is running
      ansible.builtin.package:
        name: firewalld
        state: started
        enabled: true
      when: inventory_hostname in gorups['web']

    - name: Allow HTTP traffic on web servers
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
      when: inventory_hostname in gorups['web']
      notify: Reload Firewall 

    - name: Update MOTD from Jinja2 template
      ansible.builtin.template:
        src: templates/motd.jt
        dest: /etc/motd
    
  handlers:
    - name: Reload Firewall
      ansible.builtin.service:
      name: firewalld
      state: reloaded